# Generated by Django 4.2 on 2023-04-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0002_autor_alter_produkty_options_alter_produkty_cena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='nazwisko',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='produkty',
            old_name='tytuł',
            new_name='name',
        ),
    ]
