# Generated by Django 4.2 on 2023-04-04 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0003_rename_nazwisko_autor_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='name',
            new_name='nazwisko',
        ),
        migrations.RenameField(
            model_name='produkty',
            old_name='name',
            new_name='tytuł',
        ),
        migrations.AddField(
            model_name='produkty',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.autor'),
        ),
    ]
